version: '3.8'

services:
  # PostgreSQL Primary
  postgres-primary:
    image: postgres:13
    container_name: postgres-primary
    environment:
      POSTGRES_DB: blink_db
      POSTGRES_USER: blink_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres-config/init-replication.sql:/docker-entrypoint-initdb.d/10-init-replication.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - app-network

  # PostgreSQL Replica
  postgres-replica-1:
    image: postgres:13
    container_name: postgres-replica-1
    environment:
      POSTGRES_DB: blink_db
      POSTGRES_USER: blink_user
      POSTGRES_PASSWORD: 12345
      PGUSER: replicator
      PGPASSWORD: 12345
      PGDATA: /var/lib/postgresql/data
      REPLICA_NUMBER: 1
    ports:
      - "5433:5432"
    volumes:
      - postgres_replica1_data:/var/lib/postgresql/data
      - ./postgres-config/postgresql-replica.conf:/etc/postgresql/postgresql.conf
      - ./postgres-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres-config/init-replica.sh:/docker-entrypoint-initdb.d/20-init-replica.sh
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    depends_on:
      - postgres-primary
    networks:
      - app-network

  # HAProxy với auto-failover
  haproxy:
    image: haproxy:2.4
    container_name: haproxy
    ports:
      - "5000:5000"  # HAProxy stats
      - "5434:5432"  # HAProxy PostgreSQL port (app sẽ kết nối qua đây)
    volumes:
      - ./haproxy-failover.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - postgres-primary
      - postgres-replica-1
    networks:
      - app-network

  # FastAPI Backend - kết nối qua HAProxy
  backend:
    build: .
    ports:
      - "8443:8443"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./ssl:/app/ssl
    environment:
      - DATABASE_URL=postgresql://blink_user:12345@haproxy:5432/blink_db
      - PROJECT_NAME=FastAPI Project
      - HOST=0.0.0.0
      - HTTPS_PORT=8443
      - DEBUG=True
      - HTTPS_ENABLED=true
    depends_on:
      - haproxy
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_primary_data:
  postgres_replica1_data:

networks:
  app-network:
    driver: bridge
