version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: blink_db
      POSTGRES_USER: blink_user
      POSTGRES_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db_data:

networks:
  backend-network:
    driver: bridge