# Docker Compose file for pg_auto_failover setup - Simplified version

services:
  # pg_auto_failover Monitor
  pg_auto_failover_monitor:
    build:
      context: .
      dockerfile: Dockerfile.pg_auto_failover
    container_name: pg_auto_failover_monitor
    user: postgres
    environment:
      POSTGRES_DB: pg_auto_failover
      POSTGRES_USER: pg_auto_failover
      POSTGRES_PASSWORD: 12345
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5435:5432"
    volumes:
      - pg_auto_failover_data:/var/lib/postgresql/data
    command: pg_autoctl create monitor --pgdata /var/lib/postgresql/data --hostname pg_auto_failover_monitor --pgport 5432 --auth trust --no-ssl --run
    networks:
      - pg_auto_failover_network

  # PostgreSQL Primary với pg_auto_failover
  postgres-primary:
    build:
      context: .
      dockerfile: Dockerfile.pg_auto_failover
    container_name: postgres-primary
    user: postgres
    environment:
      POSTGRES_DB: blink_db
      POSTGRES_USER: blink_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: 12345
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
    command: pg_autoctl create postgres --pgdata /var/lib/postgresql/data --hostname postgres-primary --pgport 5432 --monitor postgres://pg_auto_failover:12345@pg_auto_failover_monitor:5432/pg_auto_failover --auth trust --no-ssl --run
    depends_on:
      - pg_auto_failover_monitor
    networks:
      - pg_auto_failover_network

  # PostgreSQL Replica với pg_auto_failover
  postgres-replica-1:
    build:
      context: .
      dockerfile: Dockerfile.pg_auto_failover
    container_name: postgres-replica-1
    user: postgres
    environment:
      POSTGRES_DB: blink_db
      POSTGRES_USER: blink_user
      POSTGRES_PASSWORD: 12345
      PGUSER: replicator
      PGPASSWORD: 12345
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - postgres_replica1_data:/var/lib/postgresql/data
    command: pg_autoctl create postgres --pgdata /var/lib/postgresql/data --hostname postgres-replica-1 --pgport 5432 --monitor postgres://pg_auto_failover:12345@pg_auto_failover_monitor:5432/pg_auto_failover --auth trust --no-ssl --run
    depends_on:
      - postgres-primary
      - pg_auto_failover_monitor
    networks:
      - pg_auto_failover_network

  # HAProxy với pg_auto_failover
  haproxy:
    image: haproxy:2.4
    container_name: haproxy
    ports:
      - "5000:5000"  # HAProxy stats
      - "5434:5432"  # HAProxy PostgreSQL port
      - "8080:8080"  # Health check port
    volumes:
      - ./haproxy-pg-auto-failover.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - postgres-primary
      - postgres-replica-1
      - pg_auto_failover_monitor
    networks:
      - pg_auto_failover_network

volumes:
  postgres_primary_data:
  postgres_replica1_data:
  pg_auto_failover_data:

networks:
  pg_auto_failover_network:
    driver: bridge
