version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blink_db
      POSTGRES_USER: blink_user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend_service:
    build: .
    ports:
      - "8443:8443"   # HTTPS port
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./ssl:/app/ssl
    environment:
      - DATABASE_URL=postgresql://blink_user:12345@db:5432/blink_db
      - PROJECT_NAME=FastAPI Project
      - HOST=0.0.0.0
      - HTTPS_PORT=8443
      - DEBUG=True
      - HTTPS_ENABLED=true
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge